---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: install
  pull: default
  image: node:10
  commands:
  - echo "//registry.npmjs.org/:_authToken=$${NPM_INSTALL_TOKEN}" > ~/.npmrc
  - npm ci

- name: test8
  pull: default
  image: node:8
  depends_on:
  - install
  commands:
  - echo "//registry.npmjs.org/:_authToken=$${NPM_INSTALL_TOKEN}" > ~/.npmrc
  - npm test

- name: test10
  pull: default
  image: node:10
  depends_on:
  - install
  commands:
  - echo "//registry.npmjs.org/:_authToken=$${NPM_INSTALL_TOKEN}" > ~/.npmrc
  - npm test

- name: test12
  pull: default
  image: node:12
  depends_on:
  - install
  commands:
  - echo "//registry.npmjs.org/:_authToken=$${NPM_INSTALL_TOKEN}" > ~/.npmrc
  - npm test

- name: deploy
  pull: default
  image: node:10
  depends_on:
  - test8
  - test10
  - test12
  commands:
  - echo "//registry.npmjs.org/:_authToken=$${NPM_DEPLOY_TOKEN}" > ~/.npmrc
  - echo "unsafe-perm=true" >> ~/.npmrc
  - npm publish
  environment:
    NPM_DEPLOY_TOKEN:
      from_secret: npm_deploy_token
  when:
    event:
    - tag
