---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: install
  pull: default
  image: node:17
  commands:
  - echo "//registry.npmjs.org/:_authToken=$${NPM_INSTALL_TOKEN}" > ~/.npmrc
  - npm ci

- name: test12
  pull: default
  image: node:17
  depends_on:
  - install
  commands:
  - echo "//registry.npmjs.org/:_authToken=$${NPM_INSTALL_TOKEN}" > ~/.npmrc
  - npm test

- name: test14
  pull: default
  image: node:17
  depends_on:
  - install
  commands:
  - echo "//registry.npmjs.org/:_authToken=$${NPM_INSTALL_TOKEN}" > ~/.npmrc
  - npm test

- name: test16
  pull: default
  image: node:17
  depends_on:
  - install
  commands:
  - echo "//registry.npmjs.org/:_authToken=$${NPM_INSTALL_TOKEN}" > ~/.npmrc
  - npm test

- name: deploy
  pull: default
  image: node:17
  depends_on:
  - test12
  - test14
  - test16
  commands:
  - echo "//registry.npmjs.org/:_authToken=$${NPM_DEPLOY_TOKEN}" > ~/.npmrc
  - echo "unsafe-perm=true" >> ~/.npmrc
  - npm publish
  environment:
    NPM_DEPLOY_TOKEN:
      from_secret: npm_deploy_token
  when:
    event:
    - tag
